services:
  - type: web
    name: jobs-platform-api
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan config:clear
      php artisan key:generate --force
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_NAME
        value: Laravel
      - key: APP_URL
        value: https://jobs-platform-api.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1tiks3ipnbc73cc6f10-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: jobs_platform_api
      - key: DB_USERNAME
        value: jobs_platform_api_user
      - key: DB_PASSWORD
        value: f9rTFHlp0XtFjpGiIxc1DUZFllcYUGk2
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
